name: App Workflow

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/*'
      - '.github/*'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/madetara/crystalorb/app:1.0.${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy_image:
    runs-on: ubuntu-18.04
    needs: build_and_push
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME}}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      HOSTNAME: ${{ secrets.HOSTNAME }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: HOSTNAME, DB_PASSWORD, DB_NAME, DB_USER, DB_HOST, DB_PORT, CR_PAT, GITHUB_RUN_NUMBER
          script: |
            echo $CR_PAT | docker login ghcr.io -u madetara --password-stdin
            docker stop crystalorb
            docker rm crystalorb
            docker run -d --name crystalorb --restart unless-stopped -p 3030:3000 \
              -e DB_PASSWORD="$DB_PASSWORD" \
              -e DB_NAME="$DB_NAME" \
              -e DB_USER="$DB_USER" \
              -e DB_HOST="$DB_HOST" \
              -e DB_PORT="$DB_PORT" \
              -e HOSTNAME="$HOSTNAME" \
              --link "crystalorb-pg:$DB_HOST" \
              "ghcr.io/madetara/crystalorb/app:1.0.$GITHUB_RUN_NUMBER"
