name: Client Workflow

on:
  push:
    branches:
      - 'main'
    paths:
      - 'client/*'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          file: client/Dockerfile
          context: client/
          tags: ghcr.io/madetara/crystalorb/client:1.0.${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  deploy_image:
    runs-on: ubuntu-18.04
    needs: build_and_push
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: CR_PAT, GITHUB_RUN_NUMBER
          script: |
            echo $CR_PAT | docker login ghcr.io -u madetara --password-stdin
            docker stop crystalorb-client
            docker rm crystalorb-client
            docker run -d --name crystalorb-client --restart unless-stopped -p 3060:5000 \
              "ghcr.io/madetara/crystalorb/client:1.0.$GITHUB_RUN_NUMBER"
