name: Codestyle

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn slint

  rubocop:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop
