name: Database deployment

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/database.yaml'
  workflow_dispatch:

jobs:
  deploy_database:
    runs-on: ubuntu-20.04
    env:
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
    steps:
      - name: Deploy via docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          username: root
          envs: POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB
          script: |
            docker stop crystalorb-pg
            docker rm crystalorb-pg
            docker run \
              -v /workload/crystalorb/db:/var/lib/postgresql/data \
              --restart unless-stopped \
              --name crystalorb-pg \
              -p 5432 \
              -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
              -e POSTGRES_USER="$POSTGRES_USER" \
              -e POSTGRES_DB="$POSTGRES_DB" \
              postgres:13.1-alpine
